spring.application.name=DDP

spring.datasource.url=jdbc:mysql://localhost:3306/ddp?useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=18320996

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true